// <auto-generated />
namespace ProducerConsumer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TasksDbV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TasksDbV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202201011148519_TasksDbV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
